# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
  test -f /etc/vagrant_provisioned_at && exit
  echo 'export PS1="\\[\\033[1;32m\\][\\t][\\u@\\h \\w]\\\\$\\[\\033[0m\\] "' >> /etc/profile.d/prompt.sh
  sed -i -e "s/SELINUX=enforcing/SELINUX=disabled/g" /etc/selinux/config
  yum -y install yum-fastestmirror
  timedatectl set-timezone Asia/Tokyo
  date > /etc/vagrant_provisioned_at
SCRIPT

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/centos-6.7"
  config.vm.provider "virtualbox" do |vb|
    vb.customize [
      'modifyvm', :id,
      '--memory', '1024',
      '--cpus', 2,
      '--name', 'demo-elastichsearch',
    ]
  end
  config.vbguest.auto_update = false
  config.vm.hostname = 'demo-elastichsearch'
  config.vm.provision "shell", inline: $script
  config.vm.network "private_network", ip: "192.168.33.33"
  config.ssh.forward_agent = true

  VAGRANT_JSON = JSON.parse(Pathname(__FILE__).dirname.join('nodes', 'vagrant.json').read)
    web_dir = VAGRANT_JSON["app"]["web_dir"]
    config.vm.synced_folder "../../", web_dir, \
      :create         => true, \
      :owner          => 'vagrant', \
      :group          => 'vagrant', \
      :mount_options  => ['dmode=777,fmode=755']

    config.vm.provision :chef_solo do |chef|
       chef.cookbooks_path = ["site-cookbooks"]
       chef.roles_path = "roles"
       chef.data_bags_path = "data_bags"
       chef.provisioning_path = "/tmp/vagrant-chef"
       chef.run_list = VAGRANT_JSON.delete('run_list')
       chef.json = VAGRANT_JSON
       # old way
       #VAGRANT_JSON['run_list'].each do |recipe|
       # chef.add_recipe(recipe)
       #end if VAGRANT_JSON['run_list']
    end
end
